apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aksdemo-model-deploy
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: aksdemo-model-deploy
    spec:
      containers:
      - name: aksdemo-model-deploy
        image: mpfacr.azurecr.io/mpfplumber:c2
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: aksdemo-model-deploy
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: aksdemo-model-deploy
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: aksdemo-model-deploy
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: aksdemo-model-deploy.a6e469e777864954ba6e.centralus.aksapp.io
    http:
      paths:
      - backend:
          serviceName: aksdemo-model-deploy
          servicePort: 80
        path: /predict
